// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzEqYvm0xHumysqzQy8_y4HUKdXZmgjs',
    appId: '1:505850926191:android:00be05e241cdc5c81b699a',
    messagingSenderId: '505850926191',
    projectId: 'lets-chat-de1ff',
    storageBucket: 'lets-chat-de1ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxBK-H5Ve3-x-u63CUWmriITx9cbzpKMU',
    appId: '1:505850926191:ios:c6b41a40929064b31b699a',
    messagingSenderId: '505850926191',
    projectId: 'lets-chat-de1ff',
    storageBucket: 'lets-chat-de1ff.appspot.com',
    androidClientId: '505850926191-kdb5hujsoi3ui3delaj002hl4nihtsa7.apps.googleusercontent.com',
    iosClientId: '505850926191-p2asjihu823o0hv77af14o2u271thbjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );
}
